### PR TITLE
Address duplicate controls at catalog level in profile resolution

### PR DESCRIPTION
**Pull request by david-waltermire**
# Committer Notes

Ensure that controls defined at the catalog level are not duplicated. This fixes a bug caused during the import handling phase of profile resolution, which was "promoting" controls defined at the catalog level, causing a second copy of the control to be added. This was fixed by making controls at the catalog level always eligible for selection.

Resolves metaschema-framework/oscal-cli#60

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/metaschema-framework/liboscal-java/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you followed the guidelines in our [Contributing](https://github.com/metaschema-framework/liboscal-java/blob/main/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/metaschema-framework/liboscal-java/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all website and readme documentation affected by the changes you made?

### CODE REVIEW

**Review by aj-stein-gsa — APPROVED** [review]

**Comment by michaeldavie-amzn** [comment]
When do you expect this fix will be available in a release that can be consumed by `oscal-cli`?

**Comment by aj-stein-gsa** [comment]
> When do you expect this fix will be available in a release that can be consumed by `oscal-cli`?

Sorry for the delayed response, I was trying to find where I had not yet wrote a clear comment on this from earlier in the day. 😅 

Seeing as the release is needed in the coming days of oscal-cli and other bugs we need to revolve in metaschema-java, this codebase, and oscal-cli, can you use our [snapshot repo]() and test a recent dev build? This includes a snapshot version of `oscal-cli` and this library.

```sh
me@computer metaschema-framework_m2 % git clone https://github.com/metaschema-framework/maven2 metaschema-framework_m2
me@computer metaschema-framework_m2 % pushd metaschema-framework_m2
me@computer metaschema-framework_m2 % git remote
metaschema-framework
me@computer metaschema-framework_m2 % git branch --show-current
main
me@computer metaschema-framework_m2 % git rev-parse HEAD
4f2b437f7ef79e5df41281af9728cb96856177d1
me@computer metaschema-framework_m2 % pushd dev/metaschema/oscal/oscal-cli-enhanced/2.5.0-SNAPSHOT 
me@computer 2.5.0-SNAPSHOT % unzip  oscal-cli-enhanced-2.5.0-SNAPSHOT-oscal-cli.zip 
me@computer 2.5.0-SNAPSHOT % oscal-cli --version
oscal-cli 2.5.0-SNAPSHOT built at 2025-01-15 04:40 from branch develop (ba14f61) at Unknown
liboscal-java 5.2.0-SNAPSHOT built at 2025-01-15 04:35 from branch develop (0e18db2) at Unknown
oscal v1.1.3 built at 2025-01-15 04:35 from branch b123c11bd12c8b8f1bcc8bf85763e5775c0423e9 (b123c11) at https://github.com/usnistgov/OSCAL.git
metaschema-java 2.2.0-SNAPSHOT built at 2025-01-07T12:44:28+0000 from branch develop (d8476c3) at https://github.com/metaschema-framework/metaschema-java
metaschema 2.2.0-SNAPSHOT built at 2025-01-07T12:44:28+0000 from branch develop (7e49638) at https://github.com/metaschema-framework/metaschema.git
```

If you want to subscribe to repo notifications with the watch button on the [`oscal-cli` repo](https://github.com/metaschema-framework/oscal-cli) to follow the reason for the moment it happens, we make releases tagged on GitHub to make that easy for you to know when it is final final. Thanks for reaching out!

**Comment by michaeldavie-amzn** [comment]
Thanks! I've confirmed that the 2.5.0 snapshot build is working correctly.

**Comment by aj-stein-gsa** [comment]
> Thanks! I've confirmed that the 2.5.0 snapshot build is working correctly.

Standby for further guidance on the release. I will try to send out a custom message here.

**Pull request merged**
